
server:
  port: 80

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000  # 连接超时时间（毫秒）
    password:
    database: 0   #Redis数据库索引0-255其中一个，默认0
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 50  # 连接池中的最大空闲连接
        min-idle: 10  # 连接池中的最小空闲连接
        max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        time-between-eviction-runs: 60000

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: consumer-group1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      batch-size: 65536
      buffer-memory: 524288

  datasource:
    username: root
    password: Root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mychatgpt?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.wuzj.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



gpt:
  model:
    api-key:  2QGHQGhGDm0pdzMq6ild6duF
    secret-key: ZnqwkMCeXeoRIjMGFSFsPQTHp1MG8VRH
  # proxy:
  #   host: 127.0.0.1
  #   port: 7890